services:
  django:
    build:
      context: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/mugishadrake.site/fullchain.pem:/etc/letsencrypt/live/mugishadrake.site/fullchain.pem
      - /etc/letsencrypt/live/mugishadrake.site/privkey.pem:/etc/letsencrypt/live/mugishadrake.site/privkey.pem
    depends_on:
      - django
